/* Final 계정 생성 */
CREATE USER dajob IDENTIFIED BY dajob1710;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO dajob;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES = 10;
GRANT CREATE ANY JOB, EXECUTE ANY CLASS, MANAGE SCHEDULER TO dajob;